### PR TITLE
improvements

### PR DESCRIPTION
**Pull request by cflaviu**

### CODE REVIEW

**Comment by felixguendling** [comment]
Thank you for your help!

Some points:

- The `tuple.h` is actually generated, so the generator would need to be adapted to the style you introduced (using suffix "U" for unsigned, etc.):
https://github.com/felixguendling/cista/blob/55f852feb04f0cd27d5742d649efd29fda8facea/tools/to_tuple_generator/to_tuple_generator.cc#L116

- Please use the formatter (clang-format with the contained `.clang-format` file).

- Regarding initialization of variables, I would prefer the explicit version: `bool self_allocated_{false};` instead `bool self_allocated_{};`. It improves readability because it doesn't make me think "what is the default value for this data type"?

- It would be nice if you could make a separate commit for each type of change in the future to make it easier to review the changes:
    - adding qualifies like `const` / `noexcept`
    - adding suffixes (`32` -> `32U`)
    - code refactorings / simplifications (like `i != 0 || i != 1` -> `i > 1`)
  
  This time, it's fine.

- For the `strong<T>` usage in `vector.h` I will make adjustments. This concept for strong typing of indices is not well-rounded yet. I'm working on it still. But maybe it's better to remove it for now from the `master` branch.

**Comment by cflaviu** [comment]
Welcome!

1. I will use that.
2. The code was usually automatically formatted by my IDE. Maybe I used another editor for certain file. I will reopen and save all files applying the formatting.
3. Well I think it is a matter of perception and adaptation. {} allows the uniform initialization of all variables, basic types and complex types. I prefer that to write less and concise code. But as you prefer.
4. I reviewed the code file by file and I made the changes ad hoc.
5. That was difficult. Yes, I will remove it.
Thanks

**Comment by cflaviu** [comment]
Is it possible to run all those checks locally, on my PC?

**Comment by felixguendling** [comment]
> How can I run the sanitizers locally, on my PC?

I'm using either those delivered with the Ubuntu GCC (installable via `apt-get`) or for the fuzzing part, I use the packages from [https://apt.llvm.org/](https://apt.llvm.org/). On Mac there are downloads available [here](https://github.com/llvm/llvm-project/releases/tag/llvmorg-15.0.2) and on Windows I would probably use Ubuntu via WSL2.


> I reviewed the code file by file and I made the changes ad hoc.

This doesn't mean you need to put them all into one commit. You can select the changes you want to stage for a commit and split the changes into several commits, each with an appropriate message to describe the changes. This will make the job of reviewing your changes easier. Even if you already committed, you can amend your commit or rewrite the git history before pushing.

**Comment by cflaviu** [comment]
The formatting is failing because I'm using clang-format 12 instead of 14.

**Comment by cflaviu** [comment]
I could made different commits but the pull requests will fail due clang-format.

**Pull request closed without merging**
